//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class department
    {
        public int F_ID { get; set; }
        public string deptCode { get; set; }
        public string deptName { get; set; }
        public string deptType { get; set; }
        public string parentID { get; set; }
        public string deptLevel { get; set; }
        public string nDesc { get; set; }
        public string validState { get; set; }
        public string pefDeptHr { get; set; }
        public string pefDeptHis { get; set; }
        public string extend1 { get; set; }
        public string extend2 { get; set; }
        public string extend3 { get; set; }
    }
}
