//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class doctor
    {
        public int F_ID { get; set; }
        public string name { get; set; }
        public string ortherName { get; set; }
        public string departments { get; set; }
        public string ward { get; set; }
        public string performance { get; set; }
        public string deptidentification { get; set; }
        public string status { get; set; }
        public string employeeNo { get; set; }
        public string employeeType { get; set; }
        public string sex { get; set; }
        public string birthday { get; set; }
        public string age { get; set; }
        public string nation { get; set; }
        public string IDNo { get; set; }
        public string politicalStatus { get; set; }
        public string entrydate { get; set; }
        public string currentduty { get; set; }
        public string dutylevel { get; set; }
        public string otherduty { get; set; }
        public string cellphone { get; set; }
        public string telephone { get; set; }
        public string QQ { get; set; }
        public string email { get; set; }
        public string oldemployeeNo { get; set; }
        public string password { get; set; }
        public string certificateNo { get; set; }
        public string firstcertificateTime { get; set; }
        public string certificateTimeTo { get; set; }
        public string changedcertificateTime { get; set; }
        public string lastcertificatecompany { get; set; }
        public string bankaccount { get; set; }
    }
}
