//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class examrecord
    {
        public string F_BRBH { get; set; }
        public string BUSINESS_TYPE { get; set; }
        public string BUSINESS_ID { get; set; }
        public string DATAGENERATE_DATE { get; set; }
        public string AP08_10_002_00 { get; set; }
        public string AP01_00_022_00 { get; set; }
        public string AP04_50_057_00 { get; set; }
        public string AP04_50_056_00 { get; set; }
        public string AP06_00_048_03 { get; set; }
        public string DE04_30_018_00 { get; set; }
        public string AP04_30_018_01 { get; set; }
        public string DE04_30_019_00 { get; set; }
        public string DE04_30_020_00 { get; set; }
        public string AP02_01_115_02 { get; set; }
        public string AP02_01_115_01 { get; set; }
        public string AP04_30_059_00 { get; set; }
        public string DE04_30_015_00 { get; set; }
        public string DE04_30_017_00 { get; set; }
        public string AP04_30_046_00 { get; set; }
        public string AP08_10_025_05 { get; set; }
        public string AP08_10_025_09 { get; set; }
        public string AP08_10_026_11 { get; set; }
        public string AP08_10_013_06 { get; set; }
    }
}
