//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDM_CYC
    {
        public int F_ID { get; set; }
        public string dictType { get; set; }
        public string dictTypeDesc { get; set; }
        public string itemCode { get; set; }
        public string itemName { get; set; }
        public string valid { get; set; }
        public string extend1 { get; set; }
        public string extend2 { get; set; }
        public string extend3 { get; set; }
    }
}
