//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pathnetEntities : DbContext
    {
        public pathnetEntities()
            : base("name=pathnetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_CG_CYC> T_CG_CYC { get; set; }
        public virtual DbSet<T_CYC_FL> T_CYC_FL { get; set; }
        public virtual DbSet<T_ICD10_BM> T_ICD10_BM { get; set; }
        public virtual DbSet<T_jcxx_fs> T_jcxx_fs { get; set; }
        public virtual DbSet<T_JHP> T_JHP { get; set; }
    }
}
