//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BB
    {
        public int F_ID { get; set; }
        public string F_BBTMH { get; set; }
        public string F_BLH { get; set; }
        public string F_SQXH { get; set; }
        public string F_BBXH { get; set; }
        public string F_BBMC { get; set; }
        public string F_CQBW { get; set; }
        public string F_BZ { get; set; }
        public string F_LTSJ { get; set; }
        public string F_GDSJ { get; set; }
        public string F_JSSJ { get; set; }
        public string F_JSY { get; set; }
        public string F_BBZT { get; set; }
        public string F_BBPJ { get; set; }
        public string F_PJR { get; set; }
        public string F_PJSJ { get; set; }
    }
}
