//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BCBG
    {
        public int F_ID { get; set; }
        public string F_BLH { get; set; }
        public Nullable<int> F_BC_BGXH { get; set; }
        public string F_BC_BGYS { get; set; }
        public string F_BC_SHYS { get; set; }
        public string F_BC_BGRQ { get; set; }
        public string F_BCZD { get; set; }
        public string F_BC_BGZT { get; set; }
        public string F_BC_FZYS { get; set; }
        public string F_BC_DYZT { get; set; }
        public string F_BC_QSB_DYZT { get; set; }
        public string F_BC_BGWZ { get; set; }
        public string F_BC_BGWZ_QRSJ { get; set; }
        public string F_BC_BGWZ_QRCZY { get; set; }
        public string F_BC_BZ { get; set; }
        public string F_BC_SPARE5 { get; set; }
        public string F_BC_JXSJ { get; set; }
        public string F_BC_TSJC { get; set; }
        public string F_BC_BGGS { get; set; }
        public string F_BC_FBSJ { get; set; }
        public string F_BC_FBYS { get; set; }
    }
}
