//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BDBG
    {
        public int F_ID { get; set; }
        public string F_BLH { get; set; }
        public Nullable<int> F_BD_BGXH { get; set; }
        public string F_BD_BGYS { get; set; }
        public string F_BD_SHYS { get; set; }
        public string F_BD_BGRQ { get; set; }
        public string F_BD_BGZT { get; set; }
        public string F_BDZD { get; set; }
        public string F_BD_ZPR { get; set; }
        public string F_BD_SDRQ { get; set; }
        public string F_BD_QCYS { get; set; }
        public string F_BD_CFYY { get; set; }
        public string F_BD_ZPS { get; set; }
        public string F_BD_BZ { get; set; }
        public string F_BD_FZYS { get; set; }
        public string F_BD_DYZT { get; set; }
        public string F_BD_QSB_DYZT { get; set; }
        public string F_BD_BGWZ { get; set; }
        public string F_BD_BGWZ_QRSJ { get; set; }
        public string F_BD_BGWZ_QRCZY { get; set; }
        public string F_ZPSJ { get; set; }
        public string F_LTSJ { get; set; }
        public string F_ZPKSSJ { get; set; }
        public string F_BD_FBSJ { get; set; }
        public string F_BD_FBYS { get; set; }
        public string F_BD_BBMC { get; set; }
        public string F_BD_RYSJ { get; set; }
        public string F_BD_SPARE5 { get; set; }
    }
}
