//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BGHJ
    {
        public int F_ID { get; set; }
        public string F_BLH { get; set; }
        public string F_RQ { get; set; }
        public string F_CZY { get; set; }
        public string F_WZ { get; set; }
        public string F_DZ { get; set; }
        public string F_NR { get; set; }
        public string F_EXEMC { get; set; }
        public string F_CTMC { get; set; }
    }
}
