//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BGGD
    {
        public int F_ID { get; set; }
        public string F_BLH { get; set; }
        public string F_TKGDZT { get; set; }
        public string F_TKGDSM { get; set; }
        public string F_TKGDSJ { get; set; }
        public string F_PACSGDZT { get; set; }
        public string F_PACSGDSM { get; set; }
        public string F_PACSGDSJ { get; set; }
        public string F_YLGDZT { get; set; }
        public string F_YLGDSM { get; set; }
        public string F_YLGDSJ { get; set; }
        public Nullable<bool> f_TKflag { get; set; }
        public Nullable<int> f_tkgdcs { get; set; }
    }
}
