//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BG_PDF
    {
        public int F_ID { get; set; }
        public string F_BLBH { get; set; }
        public string F_BLH { get; set; }
        public string F_BGLX { get; set; }
        public string F_BGXH { get; set; }
        public string F_ML { get; set; }
        public string F_FILENAME { get; set; }
        public string F_JPG_errmsg { get; set; }
        public string F_BZ { get; set; }
        public string F_filePath { get; set; }
        public string F_pdfpath { get; set; }
        public string F_PDFLX { get; set; }
    }
}
