//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BG_ZLPJ
    {
        public int F_ID { get; set; }
        public string F_BLH { get; set; }
        public string F_BGZL { get; set; }
        public string F_BGZL_YYFX { get; set; }
        public string F_BGZLPJ_PJR { get; set; }
        public string F_BGZLPJ_PJSJ { get; set; }
    }
}
