//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BGFF
    {
        public long F_ID { get; set; }
        public string F_BLH { get; set; }
        public string F_JSSJ { get; set; }
        public string F_JSZ { get; set; }
        public string F_FFSJ { get; set; }
        public string F_FFZ { get; set; }
        public string F_ZT { get; set; }
        public string F_BZ { get; set; }
        public string F_BGLX { get; set; }
        public string F_bgxh { get; set; }
        public string F_DXFSSJ { get; set; }
        public string F_DXFSBZ { get; set; }
        public string F_DXZT { get; set; }
        public string F_BLBH { get; set; }
    }
}
