//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BJW_CYC
    {
        public int F_ID { get; set; }
        public Nullable<int> F_PXH { get; set; }
        public string F_BJW_MC { get; set; }
        public string F_TJYZ_FL { get; set; }
        public string F_BJW_SM { get; set; }
        public string F_DAKO { get; set; }
        public string F_LEICA { get; set; }
        public string F_ROCHE { get; set; }
        public string F_PATHCOM { get; set; }
        public string F_BXCYC { get; set; }
        public int F_SFKZ { get; set; }
        public string F_BIOCARE { get; set; }
        public string F_KFSSB { get; set; }
    }
}
