//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BLK_CS
    {
        public int F_ID { get; set; }
        public string F_BLKMC { get; set; }
        public string F_BGGS { get; set; }
        public string F_TABID { get; set; }
        public string F_BBLC_FL { get; set; }
        public string F_BSM { get; set; }
        public string F_BLHMC { get; set; }
        public int F_SF { get; set; }
        public int F_ZPS { get; set; }
        public int F_TBSID { get; set; }
        public string F_TBSMC { get; set; }
        public string F_DJBGS { get; set; }
        public string F_BBLX { get; set; }
        public string F_BLHWS { get; set; }
    }
}
