//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CYC_FL
    {
        public int F_ID { get; set; }
        public Nullable<int> F_PXID { get; set; }
        public string F_CYC_FLD { get; set; }
        public string F_CYC_FLMC { get; set; }
    }
}
