//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CYC
    {
        public int F_ID { get; set; }
        public Nullable<int> F_PXID { get; set; }
        public string F_CYC_MC { get; set; }
        public string F_CYC_FL { get; set; }
        public string F_ZJC1 { get; set; }
        public string F_ZJC2 { get; set; }
    }
}
