//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ICD10_BM
    {
        public int F_ID { get; set; }
        public string F_ICD10_BM { get; set; }
        public string F_ICD10_MC { get; set; }
        public string F_PY { get; set; }
        public string F_WB { get; set; }
        public string F_BZ { get; set; }
    }
}
