//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_jcxx_fs
    {
        public int F_id { get; set; }
        public string F_BLBH { get; set; }
        public string F_blh { get; set; }
        public string F_bglx { get; set; }
        public string F_bgxh { get; set; }
        public string F_bgzt { get; set; }
        public string F_fszt { get; set; }
        public string F_jssj { get; set; }
        public string F_fssj { get; set; }
        public Nullable<int> F_fscs { get; set; }
        public string F_bz { get; set; }
        public string F_isjpg { get; set; }
        public string F_JPG_errmsg { get; set; }
        public string f_ispdf { get; set; }
        public string GUID { get; set; }
    }
}
