//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_JHP
    {
        public int F_ID { get; set; }
        public string F_BLH { get; set; }
        public string F_XM { get; set; }
        public string F_BM { get; set; }
        public string F_JHPBH { get; set; }
        public string F_JHP_QPSM { get; set; }
        public string F_JHP_QPTMH { get; set; }
        public string F_JHP_LKSM { get; set; }
        public string F_JHP_LKH { get; set; }
        public Nullable<int> F_YJ { get; set; }
        public string F_JHPZT { get; set; }
        public string F_JCCZY { get; set; }
        public string F_JCSJ { get; set; }
        public string F_GHCZY { get; set; }
        public string F_GHSJ { get; set; }
        public string F_JHPLX { get; set; }
        public string F_JHPYY { get; set; }
        public string F_SFZH { get; set; }
        public string F_HZGX { get; set; }
        public string F_JYR { get; set; }
        public string F_LXXX { get; set; }
        public string F_BZ { get; set; }
        public string F_QPZS { get; set; }
        public string F_LKKS { get; set; }
        public int F_SXF { get; set; }
        public string F_BGYS { get; set; }
        public string F_FZYS { get; set; }
        public string F_SHYS { get; set; }
        public string F_HZDW { get; set; }
        public string F_HZRQ { get; set; }
        public string F_HZZJ { get; set; }
        public string F_HZJG { get; set; }
        public string F_HZFH { get; set; }
        public string F_JCXX_SJDW { get; set; }
    }
}
