//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_JSYZ
    {
        public int F_ID { get; set; }
        public string F_BLH { get; set; }
        public string F_JSYZH { get; set; }
        public string F_YZLX { get; set; }
        public string F_LKH { get; set; }
        public Nullable<int> F_SL { get; set; }
        public string F_SQYS { get; set; }
        public string F_SQSJ { get; set; }
        public string F_YZZT { get; set; }
        public string F_ZXSJ { get; set; }
        public string F_ZXR { get; set; }
        public string F_BZ { get; set; }
        public string F_YZLRY { get; set; }
        public string F_KDD { get; set; }
    }
}
