//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LB_CS
    {
        public int F_ID { get; set; }
        public Nullable<int> F_PXID { get; set; }
        public Nullable<int> F_PXH { get; set; }
        public string F_LX { get; set; }
        public string F_ZD { get; set; }
        public string F_MC { get; set; }
        public Nullable<int> F_KD { get; set; }
        public Nullable<int> F_ISM { get; set; }
        public int F_GJCX_PXH { get; set; }
        public Nullable<int> F_DKCX_PXH { get; set; }
    }
}
