//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LGI_WJZ_CL
    {
        public string F_ID { get; set; }
        public string F_WJZ_ID { get; set; }
        public string F_BLH { get; set; }
        public string F_CLKSXM { get; set; }
        public string F_CLRXM { get; set; }
        public Nullable<System.DateTime> F_CLSJ { get; set; }
    }
}
