//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LGI_WJZ
    {
        public string ID { get; set; }
        public string F_BLH { get; set; }
        public string F_LXBM { get; set; }
        public string F_LXMC { get; set; }
        public string F_SM { get; set; }
        public string F_SBRXM { get; set; }
        public string F_SHRXM { get; set; }
        public Nullable<System.DateTime> F_SBSJ { get; set; }
        public Nullable<int> F_LCCLZT { get; set; }
        public Nullable<System.DateTime> F_LCCLSZ { get; set; }
    }
}
