//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LK
    {
        public int F_ID { get; set; }
        public string F_BLH { get; set; }
        public string F_RWLY { get; set; }
        public string F_QCXH { get; set; }
        public string F_LKH { get; set; }
        public string F_LKZT { get; set; }
        public string F_QPZT { get; set; }
        public string F_CZY { get; set; }
        public string F_BMSJ { get; set; }
        public string F_GDZT { get; set; }
        public string F_GDCZY { get; set; }
        public string F_GDSJ { get; set; }
        public string F_BZ { get; set; }
    }
}
