//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LOG_YH
    {
        public int F_ID { get; set; }
        public string F_YHM { get; set; }
        public string F_YHMC { get; set; }
        public string F_SJ { get; set; }
        public string F_DLLX { get; set; }
        public string F_DLWZ { get; set; }
        public string F_ZDLX { get; set; }
    }
}
