//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_mq_log
    {
        public int F_id { get; set; }
        public string dateTime { get; set; }
        public string GUID { get; set; }
        public string sm { get; set; }
        public string type { get; set; }
        public string status { get; set; }
        public string msgid { get; set; }
        public string flag { get; set; }
        public string xmls { get; set; }
        public string bz { get; set; }
        public string msg { get; set; }
        public Nullable<int> F_FSCS { get; set; }
    }
}
