//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PATHCOM_TJYZ
    {
        public int F_ID { get; set; }
        public string F_BLH { get; set; }
        public string F_RWLY { get; set; }
        public string F_LKH { get; set; }
        public string F_YZH { get; set; }
        public string F_QPTMH { get; set; }
        public string F_TJH { get; set; }
        public string F_BJW { get; set; }
        public string F_ZXZT { get; set; }
        public string F_CZY { get; set; }
        public string F_CZSJ { get; set; }
        public string F_BZ { get; set; }
    }
}
