//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_QP_JGPJ
    {
        public int F_ID { get; set; }
        public string F_BLH { get; set; }
        public string F_QPJGPJ_QPTMH { get; set; }
        public string F_QPJGPJ_FL { get; set; }
        public string F_QPJGPJ_KFYY { get; set; }
        public Nullable<double> F_QPJGPJ_KFFS { get; set; }
        public string F_QPJGPJ_PJR { get; set; }
        public string F_QPJGPJ_PJSJ { get; set; }
    }
}
