//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_QP_YDY
    {
        public int F_ID { get; set; }
        public string F_BLH { get; set; }
        public string F_RWLY { get; set; }
        public string F_QCXH { get; set; }
        public string F_QPTMH { get; set; }
        public string F_QPBH { get; set; }
        public string F_QPSM { get; set; }
        public string F_CZY { get; set; }
        public string F_QPSJ { get; set; }
        public string F_DYZT { get; set; }
    }
}
