//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SF
    {
        public int F_ID { get; set; }
        public string F_BLH { get; set; }
        public string F_XM { get; set; }
        public string F_BRBH { get; set; }
        public string F_SQXH { get; set; }
        public string F_MZH { get; set; }
        public string F_ZYH { get; set; }
        public string F_SFXMDM { get; set; }
        public string F_SFXMMC { get; set; }
        public string F_DW { get; set; }
        public Nullable<double> F_DJ { get; set; }
        public Nullable<int> F_SL { get; set; }
        public Nullable<double> F_ZJ { get; set; }
        public string F_SFY { get; set; }
        public string F_SFRQ { get; set; }
        public string F_SFZT { get; set; }
        public string F_FPH { get; set; }
        public string F_XLH { get; set; }
        public string F_FYLX { get; set; }
        public string F_YZID { get; set; }
    }
}
