//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SF_XMZK
    {
        public int F_ID { get; set; }
        public string F_SJDW { get; set; }
        public string F_BRLB { get; set; }
        public string F_SFXMDM { get; set; }
        public Nullable<double> F_ZK { get; set; }
        public string F_BZ { get; set; }
    }
}
