//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SF_XM
    {
        public int F_ID { get; set; }
        public string F_SFXMDM { get; set; }
        public string F_SFXMMC { get; set; }
        public string F_SFXMSM { get; set; }
        public string F_DW { get; set; }
        public Nullable<double> F_DJ { get; set; }
        public string F_BZ { get; set; }
        public string F_ZJC1 { get; set; }
        public string F_ZJC2 { get; set; }
        public Nullable<int> F_PXH { get; set; }
    }
}
