//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SJ_CYC
    {
        public int F_ID { get; set; }
        public string F_CYC_ID { get; set; }
        public string f_CYC_MC { get; set; }
        public string f_CYC_FL { get; set; }
        public string F_CYC_SJM { get; set; }
    }
}
