//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SJ_WLZ
    {
        public int F_id { get; set; }
        public string F_wlzmc { get; set; }
        public string F_wlz { get; set; }
        public string F_zd1 { get; set; }
        public string F_zd2 { get; set; }
        public string F_zd3 { get; set; }
        public string F_zd4 { get; set; }
        public string F_zd5 { get; set; }
        public string F_zd6 { get; set; }
        public string F_zD7 { get; set; }
        public string F_zd8 { get; set; }
        public string F_zd9 { get; set; }
        public string F_zd10 { get; set; }
    }
}
