//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SJ_GYS
    {
        public int F_id { get; set; }
        public string F_gysid { get; set; }
        public string F_gysmc { get; set; }
        public string F_dz { get; set; }
        public string F_yzbm { get; set; }
        public string F_dh { get; set; }
        public string F_fax { get; set; }
        public string F_lxr { get; set; }
        public string F_email { get; set; }
        public string F_zy { get; set; }
        public string F_yddh { get; set; }
    }
}
