//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SJ_KCB
    {
        public int F_id { get; set; }
        public string F_lkdh { get; set; }
        public string F_lkrq { get; set; }
        public string F_lklx { get; set; }
        public string F_gys { get; set; }
        public string F_fph { get; set; }
        public string F_wlmc { get; set; }
        public string F_ph { get; set; }
        public string F_yxq { get; set; }
        public string F_sl { get; set; }
        public string F_sysl { get; set; }
        public string F_dj { get; set; }
        public string F_cfdd { get; set; }
        public string F_kcsl { get; set; }
        public string F_je { get; set; }
        public string F_wlz { get; set; }
        public string F_gg { get; set; }
        public string F_dw { get; set; }
        public string F_bzdw { get; set; }
        public string F_sccj { get; set; }
        public string F_scrq { get; set; }
        public string F_bz { get; set; }
        public string F_check { get; set; }
        public string F_czy { get; set; }
    }
}
