//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SJ_CKB
    {
        public int F_id { get; set; }
        public string F_ckdh { get; set; }
        public string F_ckrq { get; set; }
        public string F_lkdh { get; set; }
        public string F_cksl { get; set; }
        public string F_wlmc { get; set; }
        public string F_cklx { get; set; }
        public string F_check { get; set; }
        public string F_bz { get; set; }
        public string F_lybm { get; set; }
        public string F_lyr { get; set; }
        public string F_cky { get; set; }
        public string F_czy { get; set; }
    }
}
