//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SQD
    {
        public int F_ID { get; set; }
        public string F_JSRQ { get; set; }
        public string F_BRBH { get; set; }
        public string F_YZID { get; set; }
        public string F_SQXH { get; set; }
        public string F_BRLB { get; set; }
        public string F_MZH { get; set; }
        public string F_ZYH { get; set; }
        public string F_XM { get; set; }
        public string F_XB { get; set; }
        public string F_XBBM { get; set; }
        public string F_NL { get; set; }
        public string F_CSRQ { get; set; }
        public string F_HY { get; set; }
        public string F_DZ { get; set; }
        public string F_DH { get; set; }
        public string F_BQ { get; set; }
        public string F_CH { get; set; }
        public string F_SFZH { get; set; }
        public string F_MZ { get; set; }
        public string F_ZY { get; set; }
        public string F_SJDW { get; set; }
        public string F_SJKS { get; set; }
        public string F_SJYS { get; set; }
        public string F_SF { get; set; }
        public string F_BBMC { get; set; }
        public string F_QCBW { get; set; }
        public string F_YZXM { get; set; }
        public string F_BY1 { get; set; }
        public string F_BY2 { get; set; }
        public string F_FB { get; set; }
        public string F_LCZL { get; set; }
        public string F_LCZD { get; set; }
        public string F_KSDM { get; set; }
        public string F_KSMC { get; set; }
        public string F_YYDM { get; set; }
        public string F_YYMC { get; set; }
        public string F_SQRQ { get; set; }
        public string F_RYRQ { get; set; }
        public string F_SQYSBM { get; set; }
        public string F_SQYS { get; set; }
        public string F_SQKSBM { get; set; }
        public string F_SQKS { get; set; }
        public string F_BQDM { get; set; }
        public string F_BAH { get; set; }
        public string F_JKDABH { get; set; }
        public string F_JKKH { get; set; }
        public string F_FPH { get; set; }
        public string F_JZH { get; set; }
        public string F_JZCS { get; set; }
        public string F_JZLB { get; set; }
        public string F_JZLSH { get; set; }
        public string F_YBKH { get; set; }
        public string F_JZKH { get; set; }
        public string F_YZH { get; set; }
        public string F_YZXMBM { get; set; }
        public string F_YZXMMC { get; set; }
        public string F_ZXKSBM { get; set; }
        public string F_ZXKS { get; set; }
        public string F_SQDLX { get; set; }
        public string F_JCMD { get; set; }
        public string F_LCBS { get; set; }
        public string F_LCZZ { get; set; }
        public string F_SSRQ { get; set; }
        public string F_SZSJ { get; set; }
        public string F_YZLXBM { get; set; }
        public string F_YZLXMC { get; set; }
        public string F_ZDLB { get; set; }
        public string F_ZDLBBM { get; set; }
        public string F_messagehead { get; set; }
        public string F_messageid { get; set; }
        public string F_msgxml { get; set; }
        public string F_msg_bz { get; set; }
        public string F_DJZT { get; set; }
        public string F_sqdzt { get; set; }
        public string F_lowTime { get; set; }
        public string F_highTime { get; set; }
        public string F_priority { get; set; }
        public string F_zylsh { get; set; }
        public string F_mzlsh { get; set; }
        public string F_room { get; set; }
        public string F_imageurl { get; set; }
        public string F_jbzdbh { get; set; }
        public string F_zyjcjg { get; set; }
        public string F_icd10 { get; set; }
        public string F_jbzd { get; set; }
        public string F_yzbh { get; set; }
        public string F_fbbm { get; set; }
        public string F_patientid { get; set; }
        public string F_empiid { get; set; }
        public string F_zlh { get; set; }
        public string F_hybm { get; set; }
        public string F_zrysbm { get; set; }
        public string F_zrys { get; set; }
        public string F_zrysTel { get; set; }
        public string F_sqysTel { get; set; }
        public string F_zrks { get; set; }
        public string F_zrksbm { get; set; }
        public string F_bqbm { get; set; }
        public string F_sqdxmnr { get; set; }
        public string F_priorityCode { get; set; }
        public string F_xmpy { get; set; }
        public string F_mzbm { get; set; }
        public string F_bfh { get; set; }
        public string F_sjdwbm { get; set; }
        public string F_brlbbm { get; set; }
        public string F_sqdtxpath { get; set; }
        public string F_GUID { get; set; }
        public string F_TXZT { get; set; }
        public Nullable<int> F_XZCS { get; set; }
        public string F_XZBZ { get; set; }
        public string F_loadPath { get; set; }
    }
}
