//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SQD_BBXX
    {
        public int F_ID { get; set; }
        public string F_XH { get; set; }
        public string F_SQXH { get; set; }
        public string F_YZH { get; set; }
        public string F_BBH { get; set; }
        public string F_TMH { get; set; }
        public string F_BBMC { get; set; }
        public string F_CQBW { get; set; }
        public string F_SL { get; set; }
        public string F_LTSJ { get; set; }
        public string F_GDSJ { get; set; }
        public string F_CYSJ { get; set; }
        public string F_SJSJ { get; set; }
        public string F_FJYBM { get; set; }
        public string F_FJYXM { get; set; }
        public string F_FJYTEL { get; set; }
        public string F_FJSJ { get; set; }
    }
}
