//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SZQM
    {
        public string F_BLBH { get; set; }
        public string F_BLH { get; set; }
        public string F_BGLX { get; set; }
        public string F_BGXH { get; set; }
        public string F_CZY { get; set; }
        public string F_YW { get; set; }
        public string F_SignCert { get; set; }
        public string F_SignData { get; set; }
        public string F_QZRQ { get; set; }
    }
}
