//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SZ
    {
        public int F_ID { get; set; }
        public Nullable<int> F_PXID { get; set; }
        public string F_DL { get; set; }
        public string F_XL { get; set; }
        public string F_SM { get; set; }
        public string F_SZZ { get; set; }
    }
}
