//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TBS_XSGS_LINE
    {
        public int F_ID { get; set; }
        public Nullable<int> F_BG_ID { get; set; }
        public Nullable<int> F_TAB_ID { get; set; }
        public Nullable<int> F_CX { get; set; }
        public Nullable<int> F_CY { get; set; }
        public Nullable<int> F_SX { get; set; }
        public Nullable<int> F_SY { get; set; }
        public Nullable<int> F_COLOR { get; set; }
        public Nullable<int> F_BOLD { get; set; }
        public string F_SM { get; set; }
    }
}
