//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TBS_SY
    {
        public int F_ID { get; set; }
        public int F_BG_ID { get; set; }
        public string F_BG_MC { get; set; }
        public Nullable<int> F_BG_SORT_ID { get; set; }
        public Nullable<int> F_BG_WIDTH { get; set; }
        public Nullable<int> F_BG_HEIGHT { get; set; }
        public string F_BG_PIC { get; set; }
        public Nullable<int> F_BG_LEFT { get; set; }
        public Nullable<int> F_BG_TOP { get; set; }
        public string F_BLZD_TAG { get; set; }
        public Nullable<int> F_BJ_CX { get; set; }
        public Nullable<int> F_BJ_CY { get; set; }
        public Nullable<int> F_ISCYC { get; set; }
        public int F_BLZDFS { get; set; }
        public string F_BLZDGS { get; set; }
        public int F_XSFS { get; set; }
        public string F_XSGS { get; set; }
        public int F_GSSD { get; set; }
    }
}
