//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TBS_XSGS_LABEL
    {
        public int F_ID { get; set; }
        public Nullable<int> F_BG_ID { get; set; }
        public string F_TEXT { get; set; }
        public Nullable<int> F_TXT_INDEX { get; set; }
        public Nullable<int> F_CX { get; set; }
        public Nullable<int> F_CY { get; set; }
        public Nullable<int> F_WIDTH { get; set; }
        public Nullable<int> F_HEIGHT { get; set; }
        public string F_ZT { get; set; }
        public Nullable<int> F_ZH { get; set; }
        public Nullable<int> F_COLOR { get; set; }
        public bool F_ISBOLD { get; set; }
        public bool F_ISITALIC { get; set; }
        public bool F_ISSK { get; set; }
        public bool F_ISUL { get; set; }
    }
}
