//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_XGYJ
    {
        public int F_ID { get; set; }
        public string F_BLH { get; set; }
        public Nullable<int> F_XH { get; set; }
        public string F_YSXM { get; set; }
        public string F_XGSJ { get; set; }
        public string F_XGYJ { get; set; }
        public string F_PJYS { get; set; }
        public string F_FPJG { get; set; }
    }
}
