//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_YH
    {
        public int F_ID { get; set; }
        public string F_YHM { get; set; }
        public string F_YHMC { get; set; }
        public string F_YHBH { get; set; }
        public Nullable<int> F_YHQX { get; set; }
        public string F_YHMM { get; set; }
        public string F_DLSJ { get; set; }
        public string F_SFZX { get; set; }
        public string F_ZXWZ { get; set; }
        public Nullable<int> F_ZXSC { get; set; }
        public string F_DXYS { get; set; }
        public string F_SFZH { get; set; }
        public string F_DHHM { get; set; }
        public string F_FJH { get; set; }
        public string F_CXTS { get; set; }
        public int F_DXFPYS { get; set; }
        public string F_YH_BY1 { get; set; }
        public string F_YH_BY2 { get; set; }
    }
}
