//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB
    {
        public string XM { get; set; }
        public string XB { get; set; }
        public string NL { get; set; }
        public string SJRQ { get; set; }
        public string BLH { get; set; }
        public string MZH { get; set; }
        public string ZYH { get; set; }
        public string SJYS { get; set; }
        public string BGYS { get; set; }
        public string SJYY { get; set; }
        public string SJKS { get; set; }
        public string BGRQ { get; set; }
        public string BLK { get; set; }
        public string BY3 { get; set; }
        public string BY5 { get; set; }
        public string BBZL { get; set; }
        public string GGXZD { get; set; }
        public string TBSZD { get; set; }
        public string BBZL1 { get; set; }
        public string BBZL2 { get; set; }
        public string BBZL3 { get; set; }
        public string WSW1 { get; set; }
        public string WSW2 { get; set; }
        public string WSW3 { get; set; }
        public string JSHJY { get; set; }
        public string ztfl { get; set; }
        public string JYFF { get; set; }
        public string l13 { get; set; }
        public string qtexzl { get; set; }
        public string bbzl4 { get; set; }
        public string bbzl5 { get; set; }
        public string wsw4 { get; set; }
    }
}
