//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_BCBG_SH
    {
        public string F_BLH { get; set; }
        public Nullable<int> F_BC_BGXH { get; set; }
        public string F_BC_BGYS { get; set; }
        public string F_BC_SHYS { get; set; }
        public string F_BC_BGRQ { get; set; }
        public string F_BCZD { get; set; }
        public string F_BC_BGZT { get; set; }
    }
}
