//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_BDBG_hb
    {
        public string F_BLH { get; set; }
        public string F_XM { get; set; }
        public string F_ZYH { get; set; }
        public string F_MZH { get; set; }
        public string F_XB { get; set; }
        public string F_NL { get; set; }
        public string F_RYSJ { get; set; }
        public string F_BD_BGYS { get; set; }
        public string F_BD_FZYS { get; set; }
        public string F_BD_SHYS { get; set; }
        public string F_BD_BGRQ { get; set; }
        public string F_BD_BGZT { get; set; }
        public string F_BDZD { get; set; }
    }
}
