//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_BDBG_HFZ_BDVIEW
    {
        public string F_BLH { get; set; }
        public string F_XM { get; set; }
        public string F_ZYH { get; set; }
        public string F_XB { get; set; }
        public string F_NL { get; set; }
        public string F_CH { get; set; }
        public string F_BBMC { get; set; }
        public string F_BLZD { get; set; }
        public string F_BGRQ { get; set; }
        public string F_BGYS { get; set; }
        public string F_SHYS { get; set; }
        public string F_XSBQ { get; set; }
        public string F_SJKS { get; set; }
    }
}
