//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_brxx
    {
        public string f_unisbh { get; set; }
        public string f_sb { get; set; }
        public string f_unisb { get; set; }
        public string F_SBH { get; set; }
        public string F_JCH { get; set; }
        public string F_ZYH { get; set; }
        public string F_MZH { get; set; }
        public string F_XM { get; set; }
        public string F_XB { get; set; }
        public string F_NL { get; set; }
        public string F_BQ { get; set; }
        public string F_CH { get; set; }
        public string F_SJKS { get; set; }
        public string F_SJRQ { get; set; }
        public string F_SJYS { get; set; }
        public string F_BGRQ { get; set; }
        public string F_BGYS { get; set; }
        public string F_BGBM { get; set; }
        public string f_bgzt { get; set; }
        public string f_bw { get; set; }
        public string f_bm { get; set; }
    }
}
