//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DJB
    {
        public string F_BLK { get; set; }
        public string F_BLH { get; set; }
        public string F_BRBH { get; set; }
        public string F_SQXH { get; set; }
        public string F_YZID { get; set; }
        public string F_YZXM { get; set; }
        public string F_STUDY_UID { get; set; }
        public string F_XM { get; set; }
        public string F_XB { get; set; }
        public string F_NL { get; set; }
        public double F_AGE { get; set; }
        public string F_HY { get; set; }
        public string F_MZ { get; set; }
        public string F_ZY { get; set; }
        public string F_SFZH { get; set; }
        public string F_LXXX { get; set; }
        public string F_BRLB { get; set; }
        public string F_FB { get; set; }
        public string F_ZYH { get; set; }
        public string F_MZH { get; set; }
        public string F_BQ { get; set; }
        public string F_SJKS { get; set; }
        public string F_CH { get; set; }
        public string F_SJDW { get; set; }
        public string F_SJYS { get; set; }
        public string F_SDRQ { get; set; }
        public string F_JSY { get; set; }
        public string F_BBLX { get; set; }
        public string F_BBQK { get; set; }
        public string F_JSYY { get; set; }
        public double F_SF { get; set; }
        public string F_BBMC { get; set; }
        public string F_LCZD { get; set; }
        public string F_LCZL { get; set; }
        public string F_RYSJ { get; set; }
        public string F_QCYS { get; set; }
        public string F_QCRQ { get; set; }
        public string F_JLY { get; set; }
        public int F_LKZS { get; set; }
        public int F_CKZS { get; set; }
        public string F_FY { get; set; }
        public string F_JXSJ { get; set; }
        public string F_BLZD { get; set; }
        public string F_TSJC { get; set; }
        public string F_BGYS { get; set; }
        public string F_SHYS { get; set; }
        public string F_BGRQ { get; set; }
        public string F_CZYJ { get; set; }
        public string F_XGYJ { get; set; }
        public string F_ZDGJC { get; set; }
        public string F_YYX { get; set; }
        public string F_WFBGYY { get; set; }
        public string F_BZ { get; set; }
        public string F_BD_SFFH { get; set; }
        public string F_BGZT { get; set; }
        public string F_SFCT { get; set; }
        public string F_SFDY { get; set; }
        public string F_BGGS { get; set; }
        public string F_GDZT { get; set; }
        public int F_KNHZ { get; set; }
        public string F_ZJYJ { get; set; }
        public string F_WYYJ { get; set; }
        public int F_SFZT { get; set; }
        public string F_SFJG { get; set; }
        public string F_JBBM_CN { get; set; }
        public string F_JBBM_ENG { get; set; }
        public string F_JBMC { get; set; }
        public string F_YBLH { get; set; }
        public string F_SJCL { get; set; }
        public string F_YBLZD { get; set; }
        public string F_BGFSFS { get; set; }
        public string F_SCYS { get; set; }
        public string F_SFFH { get; set; }
        public string F_SPARE1 { get; set; }
        public string F_SPARE2 { get; set; }
        public string F_SPARE3 { get; set; }
        public string F_SPARE4 { get; set; }
        public string F_SPARE5 { get; set; }
        public string F_SPARE6 { get; set; }
        public string F_SPARE7 { get; set; }
        public string F_SPARE8 { get; set; }
        public string F_SPARE9 { get; set; }
        public string F_SPARE10 { get; set; }
        public string F_BY1 { get; set; }
        public string F_BY2 { get; set; }
        public string F_TXML { get; set; }
        public string F_ZPZT { get; set; }
        public string F_MCYJ { get; set; }
        public string F_SFJJ { get; set; }
        public int F_TBSID { get; set; }
        public string F_TBSMC { get; set; }
        public string F_QSB_DYZT { get; set; }
        public string F_BGWZ { get; set; }
        public string F_BGWZ_QRSJ { get; set; }
        public string F_BGWZ_QRCZY { get; set; }
        public string F_BBWZ { get; set; }
        public string F_LKWZ { get; set; }
        public string F_QPWZ { get; set; }
        public string F_GDCZY { get; set; }
        public string F_GDSJ { get; set; }
        public string F_GDBZ { get; set; }
        public string F_BLZD1 { get; set; }
    }
}
