//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DZP
    {
        public string F_BLH { get; set; }
        public string F_ZPZT { get; set; }
        public string F_SDRQ { get; set; }
        public string F_BLKMC { get; set; }
        public int F_ZPS { get; set; }
    }
}
