//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_HIS_TX
    {
        public int F_ID { get; set; }
        public string F_BLH { get; set; }
        public string F_TXM { get; set; }
        public string F_TXSM { get; set; }
        public Nullable<int> F_SFDY { get; set; }
        public string F_TXLB { get; set; }
    }
}
