//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_HIS_BLBG
    {
        public string F_BLH { get; set; }
        public string F_BRBH { get; set; }
        public string F_SQXH { get; set; }
        public string F_YZID { get; set; }
        public string F_YZXM { get; set; }
        public string F_XM { get; set; }
        public string F_XB { get; set; }
        public string F_NL { get; set; }
        public string F_HY { get; set; }
        public string F_ZYH { get; set; }
        public string F_MZH { get; set; }
        public string F_BQ { get; set; }
        public string F_SJKS { get; set; }
        public string F_CH { get; set; }
        public string F_SJDW { get; set; }
        public string F_SJYS { get; set; }
        public string F_SDRQ { get; set; }
        public string F_JSY { get; set; }
        public string F_BBQK { get; set; }
        public string F_JSYY { get; set; }
        public string F_BBMC { get; set; }
        public string F_LCZD { get; set; }
        public string F_QCYS { get; set; }
        public string F_QCRQ { get; set; }
        public string F_RYSJ { get; set; }
        public string F_JXSJ { get; set; }
        public string F_BLZD { get; set; }
        public string F_TSJC { get; set; }
        public string F_BGYS { get; set; }
        public string F_SHYS { get; set; }
        public string F_BGRQ { get; set; }
        public string F_BGZT { get; set; }
        public string F_WFBGYY { get; set; }
        public string F_TXML { get; set; }
        public string F_BGGS { get; set; }
        public string F_SPARE2 { get; set; }
        public string F_SPARE5 { get; set; }
        public string F_BZ { get; set; }
        public string F_FZYS { get; set; }
        public string F_SFDY { get; set; }
        public string F_YL5 { get; set; }
    }
}
