//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_JSTJYZ
    {
        public string F_BLH { get; set; }
        public string f_yzh { get; set; }
        public string F_YZLX { get; set; }
        public string F_LKH { get; set; }
        public Nullable<int> F_SL { get; set; }
        public string F_SQYS { get; set; }
        public string F_SQSJ { get; set; }
        public string F_YZZT { get; set; }
        public string F_BZ { get; set; }
        public string f_bjw { get; set; }
        public string f_lx { get; set; }
        public string f_dkrh { get; set; }
        public string F_ZXR { get; set; }
        public string F_ZXSJ { get; set; }
        public string F_ZXSB { get; set; }
        public string F_FSSJ { get; set; }
        public string F_KFSSB { get; set; }
        public string F_SFZT { get; set; }
        public string F_KDD { get; set; }
    }
}
