//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PATHCOM_TJYZ
    {
        public int 序号 { get; set; }
        public string 病理号 { get; set; }
        public string 蜡块号 { get; set; }
        public string 特检号 { get; set; }
        public string 标记物 { get; set; }
        public string 执行状态 { get; set; }
        public string 操作员 { get; set; }
        public string 操作时间 { get; set; }
        public string 备注 { get; set; }
    }
}
