//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PDF_TO_APP
    {
        public string blh { get; set; }
        public string jzlsh { get; set; }
        public string brwyh { get; set; }
        public string xm { get; set; }
        public string jclsh { get; set; }
        public string xxlx { get; set; }
        public string xxzlx { get; set; }
        public string xmid { get; set; }
        public string xmmc { get; set; }
        public string xmlj { get; set; }
        public string bgsjsj { get; set; }
        public string bgshsj { get; set; }
        public string bgys { get; set; }
        public string bglj { get; set; }
        public string bglx { get; set; }
    }
}
