//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_QP_BQDY
    {
        public int F_ID { get; set; }
        public string F_BLH { get; set; }
        public string F_RWLY { get; set; }
        public string F_LKH { get; set; }
        public string F_YZH { get; set; }
        public string F_QPTMH { get; set; }
        public Nullable<int> F_QPXH { get; set; }
        public string F_QPBH { get; set; }
        public string F_QPSM { get; set; }
        public string F_CZY { get; set; }
        public string F_QPSJ { get; set; }
        public string F_DYZT { get; set; }
        public string F_JGPJ { get; set; }
        public string F_PJR { get; set; }
        public string F_QPZT { get; set; }
        public string F_QPTMH2 { get; set; }
        public string F_GDZT { get; set; }
        public string F_GDCZY { get; set; }
        public string F_GDSJ { get; set; }
        public string F_BZ { get; set; }
        public string F_ZZMC { get; set; }
        public string F_SM { get; set; }
        public string F_TJH { get; set; }
    }
}
