//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_QPGZB_QCMX
    {
        public int F_ID { get; set; }
        public Nullable<int> F_PXID { get; set; }
        public string F_BLH { get; set; }
        public string F_RWLY { get; set; }
        public string F_QCXH { get; set; }
        public string F_ZZMC { get; set; }
        public string F_CKS { get; set; }
        public string F_QCYS { get; set; }
        public string F_QCRQ { get; set; }
        public string F_BMZT { get; set; }
        public string F_SM { get; set; }
        public string F_BZ { get; set; }
    }
}
