//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TBS
    {
        public string XM { get; set; }
        public string XB { get; set; }
        public string NL { get; set; }
        public string SQXH { get; set; }
        public string BH { get; set; }
        public string KS { get; set; }
        public string QYRQ { get; set; }
        public string MYD { get; set; }
        public string XBL { get; set; }
        public string JGXB { get; set; }
        public string HSXB { get; set; }
        public string BDYJ { get; set; }
        public string DCGR { get; set; }
        public string NZGR { get; set; }
        public string HPV { get; set; }
        public string BZGR { get; set; }
        public string YJ1 { get; set; }
        public string YJ2 { get; set; }
        public string BGYS { get; set; }
        public string BGRQ { get; set; }
    }
}
