//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_tbs_yxl
    {
        public string F_BLH { get; set; }
        public string F_XM { get; set; }
        public string F_LXXX { get; set; }
        public string F_SDRQ { get; set; }
        public string F_BGRQ { get; set; }
        public string F_BGYS { get; set; }
        public string F_TBS_MPFX { get; set; }
    }
}
