//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TJ_BD
    {
        public string F_BLK { get; set; }
        public string F_BGYS { get; set; }
        public string F_SHYS { get; set; }
        public string F_FZYS { get; set; }
        public string F_BGRQ { get; set; }
    }
}
