//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TJ_BGFF
    {
        public string F_BLH { get; set; }
        public string F_XM { get; set; }
        public string F_XB { get; set; }
        public string F_NL { get; set; }
        public string F_ZYH { get; set; }
        public string F_SJDW { get; set; }
        public string F_SJKS { get; set; }
        public string F_SDRQ { get; set; }
        public string F_BLK { get; set; }
        public string F_SFDY { get; set; }
        public string F_BBLX { get; set; }
    }
}
