//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TJ_JCXX
    {
        public string F_BLK { get; set; }
        public string F_JSY { get; set; }
        public string F_JLY { get; set; }
        public string F_SJYS { get; set; }
        public string F_SJKS { get; set; }
        public string F_SJDW { get; set; }
        public string F_BGYS { get; set; }
        public string F_SHYS { get; set; }
        public string F_FZYS { get; set; }
        public string F_BGRQ { get; set; }
        public string F_BGLRY { get; set; }
        public Nullable<double> F_SF { get; set; }
        public string F_SFFH { get; set; }
        public string F_BD_SFFH { get; set; }
        public string F_RQ { get; set; }
        public string F_YL1 { get; set; }
    }
}
