//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGI.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_TJ_YSGZL_TJYZ
    {
        public string F_BLK { get; set; }
        public string F_YZLX { get; set; }
        public string F_ZXR { get; set; }
        public string F_SQYS { get; set; }
        public string F_RQ { get; set; }
        public string F_BLH { get; set; }
    }
}
